name: Tests
run-name: Tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: installing test dependencies
        run: pip install -r requirements.test.txt
      - name: isort check
        run: python -m isort . --check-only
      - name: black check
        run: python -m black . --check
      - name: unit tests
        run: PYTHONPATH=../ python ./log_analyzer/tests/test_log_analyzer.py
