name: Tests
run-name: Tests
on: [push]
jobs:
  Log-Analyzer-Tests:
    runs-on: ubuntu-latest
    env:
      app_name: log_analyzer
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: installing test dependencies
        run: pip install -r requirements.test.txt
      - name: isort check
        working-directory: ${{ env.app_name }}
        run: python -m isort . --check-only
      - name: black check
        working-directory: ${{ env.app_name }}
        run: python -m black . --check
      - name: unit tests
        working-directory: ${{ env.app_name }}/tests/
        run: PYTHONPATH=../ python test_${{ env.app_name }}.py
  Scoring-API-Tests:
    runs-on: ubuntu-latest
    env:
      app_name: scoring_api
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: installing dependencies
        run: pip install -r requirements.txt
      - name: installing test dependencies
        run: pip install -r requirements.test.txt
      - name: isort check
        working-directory: ${{ env.app_name }}
        run: python -m isort . --check-only
      - name: black check
        working-directory: ${{ env.app_name }}
        run: python -m black . --check
      - name: unit tests
        working-directory: ${{ env.app_name }}
        run: pytest test.py
